"""Update audit trails

Revision ID: 06179be03895
Revises: 9a72b66115b6
Create Date: 2026-03-12 00:06:16.398153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '06179be03895'
down_revision: Union[str, None] = '9a72b66115b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_trails',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('changes', sqlite.JSON(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('audit_trail')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_trail',
    sa.Column('action', sa.VARCHAR(length=100), nullable=True),
    sa.Column('actor', sa.VARCHAR(length=100), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('audit_trails')
    # ### end Alembic commands ###
