"""extend_workflow_case

Revision ID: 410ee1689864
Revises: 436579581f38
Create Date: 2026-03-12 16:55:40.986867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '410ee1689864'
down_revision: Union[str, None] = '436579581f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_cases', sa.Column('incident_id', sa.Uuid(), nullable=True))
    op.add_column('workflow_cases', sa.Column('assigned_to', sa.Uuid(), nullable=True))
    op.add_column('workflow_cases', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('workflow_cases', sa.Column('ai_evaluation', sqlite.JSON(), nullable=True))
    op.add_column('workflow_cases', sa.Column('human_decision', sqlite.JSON(), nullable=True))
    op.add_column('workflow_cases', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_cases', 'updated_at')
    op.drop_column('workflow_cases', 'human_decision')
    op.drop_column('workflow_cases', 'ai_evaluation')
    op.drop_column('workflow_cases', 'confidence_score')
    op.drop_column('workflow_cases', 'assigned_to')
    op.drop_column('workflow_cases', 'incident_id')
    # ### end Alembic commands ###
