"""add account lockout fields

Revision ID: bf80d2937990
Revises: 410ee1689864
Create Date: 2026-03-13 23:26:54.616336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf80d2937990'
down_revision: Union[str, None] = '410ee1689864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use server_default='0' so SQLite can add the NOT NULL column to existing rows
    op.add_column('users', sa.Column(
        'failed_login_attempts', sa.Integer(), nullable=False, server_default='0'
    ))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###
