"""Initial schema

Revision ID: de82e5e1a53d
Revises: 
Create Date: 2026-03-11 23:31:35.568057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision: str = 'de82e5e1a53d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_trail',
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('external_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('income_bracket', sa.Enum('low', 'medium', 'high', 'very_high', name='incomebracket'), nullable=False),
    sa.Column('annual_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('risk_tolerance', sa.Enum('conservative', 'moderate', 'aggressive', name='risktolerance'), nullable=True),
    sa.Column('segment', sa.Enum('mass', 'affluent', 'hnw', 'uhnw', name='segment'), nullable=True),
    sa.Column('kyc_status', sa.Enum('pending', 'verified', 'expired', 'flagged', name='kycstatus'), nullable=True),
    sa.Column('relationship_manager_id', sa.String(length=50), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_customers_external_id'), 'customers', ['external_id'], unique=True)
    op.create_index(op.f('ix_customers_relationship_manager_id'), 'customers', ['relationship_manager_id'], unique=False)
    op.create_table('product_catalog',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Enum('deposit', 'equity', 'bond', 'fund', 'insurance', 'loan', name='catalogcategory'), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='productrisklevel'), nullable=True),
    sa.Column('min_investment', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_return_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fee_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_cases',
    sa.Column('case_type', sa.Enum('fraud', 'risk', 'advisory', 'compliance', name='casetype'), nullable=True),
    sa.Column('status', sa.Enum('created', 'ai_processing', 'ai_evaluated', 'pending_review', 'in_review', 'human_decided', 'escalated', 'closed', name='casestatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('customer_id', app.models.base.GUID(), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('account_type', sa.Enum('checking', 'savings', 'investment', 'loan', 'credit_card', name='accounttype'), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('active', 'dormant', 'closed', 'frozen', name='accountstatus'), nullable=False),
    sa.Column('opened_date', sa.Date(), nullable=False),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    op.create_index(op.f('ix_accounts_customer_id'), 'accounts', ['customer_id'], unique=False)
    op.create_table('product_holdings',
    sa.Column('customer_id', app.models.base.GUID(), nullable=False),
    sa.Column('product_id', app.models.base.GUID(), nullable=False),
    sa.Column('product_type', sa.Enum('deposit', 'equity', 'bond', 'mutual_fund', 'etf', 'insurance', 'loan', name='productcategory'), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('acquisition_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_holdings_customer_id'), 'product_holdings', ['customer_id'], unique=False)
    op.create_table('risk_incidents',
    sa.Column('customer_id', app.models.base.GUID(), nullable=False),
    sa.Column('incident_type', sa.Enum('fraud_alert', 'aml_flag', 'credit_breach', 'suspicious_txn', 'identity_theft', name='incidenttype'), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='incidentseverity'), nullable=True),
    sa.Column('status', sa.Enum('open', 'investigating', 'resolved', 'dismissed', 'escalated', name='incidentstatus'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('related_transaction_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_incidents_customer_id'), 'risk_incidents', ['customer_id'], unique=False)
    op.create_table('transactions',
    sa.Column('account_id', app.models.base.GUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_type', sa.Enum('debit', 'credit', 'transfer', 'payment', 'withdrawal', 'deposit', name='transactiontype'), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('channel', sa.Enum('online', 'mobile', 'branch', 'atm', 'phone', name='transactionchannel'), nullable=True),
    sa.Column('status', sa.Enum('completed', 'pending', 'failed', 'reversed', name='transactionstatus'), nullable=True),
    sa.Column('risk_flag', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_timestamp'), 'transactions', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_timestamp'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_risk_incidents_customer_id'), table_name='risk_incidents')
    op.drop_table('risk_incidents')
    op.drop_index(op.f('ix_product_holdings_customer_id'), table_name='product_holdings')
    op.drop_table('product_holdings')
    op.drop_index(op.f('ix_accounts_customer_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('workflow_cases')
    op.drop_table('product_catalog')
    op.drop_index(op.f('ix_customers_relationship_manager_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_external_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('audit_trail')
    # ### end Alembic commands ###
